// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARk8Xze1NbQNpz2k_L2DMVWco75ce3g-I',
    appId: '1:1066096605461:web:d9f4b6c13933afb7c7111c',
    messagingSenderId: '1066096605461',
    projectId: 'aquabalance-tool',
    authDomain: 'aquabalance-tool.firebaseapp.com',
    storageBucket: 'aquabalance-tool.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmHhGwISSuoIiMoDHoBnbXgR0bX8b01cw',
    appId: '1:1066096605461:android:5f814b83fbd8050dc7111c',
    messagingSenderId: '1066096605461',
    projectId: 'aquabalance-tool',
    storageBucket: 'aquabalance-tool.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO_GwT322kaUe5-BlvyQrsFZouePONg5g',
    appId: '1:1066096605461:ios:af90ff5db4e11cbfc7111c',
    messagingSenderId: '1066096605461',
    projectId: 'aquabalance-tool',
    storageBucket: 'aquabalance-tool.firebasestorage.app',
    iosBundleId: 'com.o2tech.aquabalance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO_GwT322kaUe5-BlvyQrsFZouePONg5g',
    appId: '1:1066096605461:ios:af90ff5db4e11cbfc7111c',
    messagingSenderId: '1066096605461',
    projectId: 'aquabalance-tool',
    storageBucket: 'aquabalance-tool.firebasestorage.app',
    iosBundleId: 'com.o2tech.aquabalance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARk8Xze1NbQNpz2k_L2DMVWco75ce3g-I',
    appId: '1:1066096605461:web:d1ff2575dd8062c7c7111c',
    messagingSenderId: '1066096605461',
    projectId: 'aquabalance-tool',
    authDomain: 'aquabalance-tool.firebaseapp.com',
    storageBucket: 'aquabalance-tool.firebasestorage.app',
  );
}
